#!/usr/bin/env python3
# SPDX-License-Identifier: LicenseRef-PolyForm-Noncommercial-1.0.0
"""Generate requirements.lock (full closure, hash-pinned) from requirements.in.

1. Resolve the closure with `pip install --dry-run --ignore-installed --report`
   for each target platform tag below (CPython 3.11-3.13 wheels).
2. For every resolved name==version, take ALL sha256 digests PyPI publishes for
   that release (wheels for every OS + sdist), so one lock serves macOS and
   Windows under `pip install --require-hashes --no-deps`.

Needs network (pypi.org). Stdlib only. Usage: python tools/lock_deps.py [--check]
--check exits 1 if requirements.lock is missing or stale versus requirements.in.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
IN, LOCK = ROOT / "requirements.in", ROOT / "requirements.lock"
# (platform tag, python version) pairs the lock must cover.
# ponytail: Intel Macs are not covered (no onnxruntime/ctranslate2 wheels); they use whisper.cpp.
TARGETS = [(plat, ver) for plat in ("macosx_14_0_arm64", "macosx_13_0_x86_64", "win_amd64") for ver in ("3.11", "3.12", "3.13")]


def direct_reqs() -> list[str]:
    return [l.split("#")[0].strip() for l in IN.read_text(encoding="utf-8").splitlines()
            if l.split("#")[0].strip()]


def resolve(reqs: list[str], platform: str | None, pyver: str | None) -> dict[str, str]:
    with tempfile.TemporaryDirectory() as td:
        rep = Path(td) / "report.json"
        cmd = [sys.executable, "-m", "pip", "install", "--dry-run", "--ignore-installed",
               "--quiet", "--report", str(rep)]
        if platform:
            cmd += ["--only-binary=:all:", "--platform", platform, "--python-version", pyver,
                    "--target", str(Path(td) / "t")]
        subprocess.run(cmd + reqs, check=True)
        data = json.loads(rep.read_text(encoding="utf-8"))
    return {i["metadata"]["name"].lower(): i["metadata"]["version"] for i in data["install"]}


def hashes(name: str, version: str) -> list[str]:
    with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json", timeout=60) as r:
        data = json.load(r)
    return sorted({u["digests"]["sha256"] for u in data["urls"]})


def render(pins: dict[str, str]) -> str:
    out = ["# GENERATED by tools/lock_deps.py from requirements.in -- do not edit.",
           "# pip install --require-hashes --no-deps -r requirements.lock"]
    for name in sorted(pins):
        hs = hashes(name, pins[name])
        out.append(f"{name}=={pins[name]} \\")
        out += [f"    --hash=sha256:{h}" + (" \\" if i < len(hs) - 1 else "") for i, h in enumerate(hs)]
    return "\n".join(out) + "\n"


def stale() -> bool:
    if not LOCK.exists():
        return True
    locked = dict(re.findall(r"^([A-Za-z0-9_.-]+)==(\S+)", LOCK.read_text(encoding="utf-8"), re.M))
    locked = {k.lower(): v for k, v in locked.items()}
    for req in direct_reqs():
        n, v = req.split("==")
        if locked.get(n.lower()) != v:
            return True
    return False


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    if a.check:
        s = stale()
        print("requirements.lock is " + ("STALE or missing" if s else "up to date"))
        return 1 if s else 0
    reqs = direct_reqs()
    pins: dict[str, str] = {}
    for plat in TARGETS:
        for n, v in resolve(reqs, *plat).items():
            if pins.setdefault(n, v) != v:
                raise SystemExit(f"version split for {n}: {pins[n]} vs {v}; pin it in requirements.in")
    LOCK.write_text(render(pins), encoding="utf-8")
    print(f"wrote {LOCK.name}: {len(pins)} packages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
